### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by Myjunk-Juan** [thesfn/SAM#1]
The app does not request file Permissions, only media permissions. This does not allow the app to properly scan or find files in the android filesystem..

**Comment by thesfn** [comment]
This issue has been documented and a fix / update is in progress and will be available soon
Affected OS : Android 11 and higher;
Cause : Legacy Architecture 
Thank you for your support.

**Comment by thesfn** [comment]
The 0 sam found bug is fixed and several improvement added.
